### ISSUE TITLE
Z3 mappings implementation

### ISSUE THREAD

**Issue by epatrizio** [formalsec/encoding#47]
Hello,

I'm currently working on improving `Owi`'s test coverage, especially for symbolic interpretation.
https://github.com/OCamlPro/owi/pull/96

Some `z3 mappings` are missing.
For example, `Ceil` and `Floor` float unop.
https://github.com/formalsec/encoding/blob/4cd856eacc9fb23fdfcf4fd0b21d0de311ac2ae7/lib/z3_mappings.ml#L408

Do you plan to implement them?

Thanks

**Comment by filipeom** [comment]
Hello!

**Comment by epatrizio** [comment]
Thanks a lot, perfect :ok_hand: 

> There's no direct Z3 operator for `Ceil` or `Floor`

@zapashcanon assumed this point :wink:
